name: deploy-manifests-staging

on:
  push:
    branches:
      - staging
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-staging
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-staging
